metrics.path.app: dojrzewatr
rest.api.urls.to.list: .*brew.*

stubrunner.stubs:
  repository.root: http://54.171.73.213:8081/nexus/content/repositories/releases/

stubrunner:
  use-microservice-definitions: true